### ISSUE TITLE
Does your code replicate the stepwise progression of alpha to chaos?

### ISSUE THREAD

**Issue by MKLau** [HFpostdoc/unstable_states#1]
![alpha_chaos](https://cloud.githubusercontent.com/assets/5342857/3056425/a0529022-e1ca-11e3-8866-fdda696d239a.png)

**Comment by amellison17** [comment]
Nice graphs. What's the model?

A.

**Comment by MKLau** [comment]
Thanks, I'm making sure the functions work.

The model's from May's 1976 Nature paper, Nt+1 = Nt_(a - b_Nt), where N0 = 1, b = 0.1 and a = 2.707, 3.414, 3.570 and 3.700 (left to right). The phase diagrams are below there associated time series.

**Comment by amellison17** [comment]
great, thanks.
aaron

**Comment by MKLau** [comment]
Looks good, now switching to the canonical form (i.e., May 1976 Equation 3).
