### ISSUE TITLE
Convergent Cross Mapping 

### ISSUE THREAD

**Issue by MKLau** [HFpostdoc/unstable_states#55]
Based on Taken's Theorem, a series of lagged vectors taken from a time series can be used to reconstruct the manifold that created the time series.

This can be seen in the following plots using the Lorenz "Butterfly" attractor.

Top figure = Lorenz manifold
Bottom figure = reconstructed (aka. shadow) manifold using time lags (tau = 2) using three time lags

![screen shot 2014-09-01 at 4 28 54 pm](https://cloud.githubusercontent.com/assets/5342857/4111887/0b7a452a-3216-11e4-9eda-a40401e08b16.png)

![screen shot 2014-09-01 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/5342857/4111885/0530263a-3216-11e4-9c36-c5ee308120da.png)

**Comment by MKLau** [comment]
Random vector

![screen shot 2014-09-01 at 4 41 44 pm](https://cloud.githubusercontent.com/assets/5342857/4111956/dc244332-3217-11e4-97d9-d9c1345a94ce.png)

**Comment by amellison17** [comment]
Matt - this is really cool. Am I right that we can apply it to the simulated pitcher plant data and to Amanda's O2-time-series data?

Aaron

**Comment by MKLau** [comment]
Great!

Yes, any time series with an underlying manifold.

I still need to program a nearest neighbors algorithm to do the cross mapping, but currently we can use the time lag function I wrote to generate "shadow manifold" plots.

These are essentially phase plots but can be interpreted as having properties of the true manifold based on Taken's Theorem.

Matt

Sent using CloudMagichttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=5.1.3&pv=4.1.2

On Mon, Sep 01, 2014 at 7:59 PM, Aaron Ellison <notifications@github.com<mailto:notifications@github.com>> wrote:

Matt - this is really cool. Am I right that we can apply it to the simulated pitcher plant data and to Amanda's O2-time-series data?

Aaron

**Comment by amellison17** [comment]
wicked cool!
Aaron

**Comment by MKLau** [comment]
Here is the method applied to the Sensitivity O2 data:

E = 3 and tau = 25

**Run 1**
![screen shot 2014-09-02 at 10 08 12 am](https://cloud.githubusercontent.com/assets/5342857/4119360/40ced29c-32aa-11e4-9148-bc219ab9b0eb.png)

![screen shot 2014-09-02 at 10 27 55 am](https://cloud.githubusercontent.com/assets/5342857/4119679/c63dbc52-32ac-11e4-9237-0f8ca70c78b5.png)

**Run 51**
![screen shot 2014-09-02 at 10 09 08 am](https://cloud.githubusercontent.com/assets/5342857/4119365/49775d1a-32aa-11e4-8514-fb72e433b6ac.png)

**Run 91**
![screen shot 2014-09-02 at 10 11 32 am](https://cloud.githubusercontent.com/assets/5342857/4119386/765a3e10-32aa-11e4-835a-ab97504ebee3.png)

**Comment by MKLau** [comment]
Here is time lags 1 and 2 for Run 1 colored by time:

![screen shot 2014-09-02 at 10 22 30 am](https://cloud.githubusercontent.com/assets/5342857/4119576/11060092-32ac-11e4-8ca5-a4bba84d4306.png)

Here is time lags 1 and 2 for Run 51 colored by time:
![screen shot 2014-09-02 at 10 23 57 am](https://cloud.githubusercontent.com/assets/5342857/4119601/396ea7fa-32ac-11e4-95c4-56523acfe276.png)

Here is time lags 1 and 2 for Run 91 colored by time:

![screen shot 2014-09-02 at 10 24 57 am](https://cloud.githubusercontent.com/assets/5342857/4119616/5240cbf0-32ac-11e4-922e-5b963135f147.png)
